version: '3.8'

services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: /bin/sh
    command: -c "minio server /data --console-address ":9001" & sleep 5 && mc alias set minio http://localhost:9000 minioadmin minio123 && mc quota set minio/cats --size 10m && wait"
    tmpfs:
      - /data:size=20m

  loader:
    build: ./loader
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minio123
